// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwuCXunRMWHqWGZ2KA9QF4yPDow9Xe-xU',
    appId: '1:45777990788:web:bb57dd3e3d7c9f7f047ed1',
    messagingSenderId: '45777990788',
    projectId: 'clean-art-eb945',
    authDomain: 'clean-art-eb945.firebaseapp.com',
    storageBucket: 'clean-art-eb945.appspot.com',
    measurementId: 'G-GS7MBXV0YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDleaOxkX0vAmtJxsPCwOO9mUJLx6XEYno',
    appId: '1:45777990788:android:43492d8096f80ffb047ed1',
    messagingSenderId: '45777990788',
    projectId: 'clean-art-eb945',
    storageBucket: 'clean-art-eb945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHo-AtAGxW2TVFNw8u_2HzK4ki8UpHv4',
    appId: '1:45777990788:ios:3e224c0b47d613ff047ed1',
    messagingSenderId: '45777990788',
    projectId: 'clean-art-eb945',
    storageBucket: 'clean-art-eb945.appspot.com',
    iosBundleId: 'com.example.cleanArt',
  );
}
